name: SignSetHome
version: '${project.version}'
main: me.liamsnow.signsethome.SignSetHome
api-version: 1.19
authors: [ LiamSnow ]
website: https://liamsnow.com
depend: ['GriefPrevention']
commands:
  sethome:
    description: Sets your home location that can be teleported to from Spawn.
    usage: /<command>
  sshreload:
    description: Reloads the configuration for SignSetHome.
    usage: /<command>
    aliases: [signsethomereload]

