name: SignSetHome
version: '${project.version}'
main: me.liamsnow.signsethome.SignSetHome
api-version: 1.19
authors: [ LiamSnow ]
website: https://liamsnow.com
depend: ['GriefPrevention']
commands:
  sethome:
    description: Sets your home location that can be teleported to from Spawn.
    usage: /<command>
    default: true
  signsethome-reload:
    description: Reloads the config & database for SignSetHome.
    usage: /<command>
    aliases: [ssh-reload]
    default: op
  signsethome-setspawn:
    description: Sets the spawn for SignSetHome.
    usage: /<command>
    aliases: [ ssh-setspawn ]
    default: op
  signsethome-setwarplobby:
    description: Sets the warp lobby for SignSetHome.
    usage: /<command>
    aliases: [ ssh-setwarplobby ]
    default: op
  signsethome-givewarplobbysign:
    description: Gives player the special warp lobby sign.
    usage: /<command>
    aliases: [ ssh-givewarplobbysign ]
    default: op

