name: GriefPrevention-Territory-Display
version: '${project.version}'
main: me.liamsnow.griefpreventionterritorydisplay.GriefPreventionTerritoryDisplay
api-version: 1.19
authors: [ LiamSnow ]
depend: ['GriefPrevention']
website: https://liamsnow.com
